import Link from 'next/link';

const dimensions = [
  { name: 'Technical Depth', score: 87, confidence: 94, color: 'bg-brand-green' },
  { name: 'System Design', score: 72, confidence: 68, color: 'bg-brand-yellow' },
  { name: 'Behavioral', score: 91, confidence: 89, color: 'bg-brand-green' },
  { name: 'Communication', score: 78, confidence: 82, color: 'bg-brand-green' },
];

export function SampleReport() {
  return (
    <section className="bg-paper py-20">
      <div className="mx-auto max-w-7xl px-6">
        <div className="mx-auto max-w-3xl text-center">
          <p className="font-mono text-xs uppercase tracking-[0.25em] text-brand-orange">
            Candidate Report
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight text-ink md:text-4xl">
            See what you get
          </h2>
          <p className="mt-4 text-lg text-ink-light">
            Every candidate receives a detailed report with scores, confidence levels, and
            evidence trails. No black boxes.
          </p>
        </div>

        {/* Sample Report Card */}
        <div className="mx-auto mt-12 max-w-2xl overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-xl">
          {/* Report Header */}
          <div className="border-b border-gray-200 bg-paper-off px-8 py-6">
            <div className="flex items-start justify-between">
              <div>
                <p className="text-sm text-ink-muted">Candidate Report</p>
                <h3 className="mt-1 text-xl font-bold text-ink">Priya Sharma</h3>
                <p className="text-sm text-ink-light">Senior Backend Engineer &middot; GCC Engineering Team</p>
              </div>
              <div className="text-right">
                <div className="inline-flex items-center gap-2 rounded-full bg-brand-green/10 px-4 py-1.5">
                  <div className="h-2 w-2 rounded-full bg-brand-green" />
                  <span className="text-sm font-semibold text-brand-green">Strong Hire</span>
                </div>
              </div>
            </div>
          </div>

          {/* Overall Score */}
          <div className="border-b border-gray-200 px-8 py-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-ink-muted">Overall Score</p>
                <p className="text-4xl font-extrabold text-ink">82<span className="text-lg font-normal text-ink-muted">/100</span></p>
              </div>
              <div className="text-right">
                <p className="text-sm font-medium text-ink-muted">Confidence</p>
                <div className="flex items-center gap-2">
                  <div className="h-2 w-24 overflow-hidden rounded-full bg-gray-200">
                    <div className="h-full w-[83%] rounded-full bg-brand-green" />
                  </div>
                  <span className="text-sm font-bold text-brand-green">83%</span>
                </div>
              </div>
            </div>
          </div>

          {/* Dimension Scores */}
          <div className="px-8 py-6">
            <p className="mb-4 text-sm font-semibold text-ink">Dimension Scores</p>
            <div className="space-y-4">
              {dimensions.map((dim) => (
                <div key={dim.name} className="flex items-center gap-4">
                  <span className="w-32 text-sm text-ink-light">{dim.name}</span>
                  <div className="flex flex-1 items-center gap-3">
                    <div className="h-2 flex-1 overflow-hidden rounded-full bg-gray-100">
                      <div
                        className={`h-full rounded-full ${dim.color}`}
                        style={{ width: `${dim.score}%` }}
                      />
                    </div>
                    <span className="w-8 text-right text-sm font-semibold text-ink">{dim.score}</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <div className={`h-1.5 w-1.5 rounded-full ${dim.confidence >= 80 ? 'bg-brand-green' : 'bg-brand-yellow'}`} />
                    <span className="text-xs text-ink-muted">{dim.confidence}% conf.</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Report Footer */}
          <div className="border-t border-gray-200 bg-paper-off px-8 py-4">
            <p className="text-xs text-ink-muted">
              Report generated by LayersRank &middot; Multi-model consensus with adaptive follow-up
            </p>
          </div>
        </div>

        <div className="mt-8 text-center">
          <Link
            href="/resources"
            className="inline-flex items-center gap-2 rounded-lg bg-brand-yellow px-6 py-3 text-sm font-semibold text-ink transition-colors hover:bg-brand-orange"
          >
            Download Full Sample Report
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </Link>
        </div>
      </div>
    </section>
  );
}
